### ISSUE TITLE
Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

### ISSUE THREAD

**Issue by ghost** [MoOx/atom-monokai-tweaked-ui#13]
In index.less: Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.
If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

**Comment by MoOx** [comment]
@davi-machado do you want to be a maintainer of this package ?

**Comment by MoOx** [comment]
(I don't use it for now)

**Comment by ghost** [comment]
No man... I just reported the issue automatically trought atom. I'm sorry.

Em seg, 11 de mai de 2015 às 09:04, Maxime Thirouin <
notifications@github.com> escreveu:

**Comment by MoOx** [comment]
Ok cool. Thanks for the feedback :)
